//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub summary: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub aggregated_rating: Option<f32>,
    pub themes: Option<String>,
    pub igdb_url: String,
    pub first_release_date: Option<DateTimeUtc>,
    pub franchise: Option<String>,
    pub genres: Option<String>,
    pub game_modes: Option<String>,
    pub supports_online_multiplayer: Option<bool>,
    pub platforms: Option<String>,
    pub cover_art_url: Option<String>,
    pub artwork_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
